# Generated by Django 6.0.3 on 2026-03-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis projektu')),
                ('technologies', models.CharField(max_length=500, verbose_name='Użyte technologie')),
                ('repo_url', models.URLField(blank=True, verbose_name='Link do repozytorium')),
                ('demo_url', models.URLField(blank=True, verbose_name='Link do demo')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('submitted', 'Oddany')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
        ),
    ]
