# Generated by Django 6.0.3 on 2026-03-23 21:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa kryterium')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('max_points', models.PositiveIntegerField(default=10, verbose_name='Max punktów')),
                ('weight', models.FloatField(default=1.0, verbose_name='Waga')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='hackathon.hackathon')),
            ],
            options={
                'verbose_name_plural': 'Criteria',
            },
        ),
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='hackathon.hackathon')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('jury', 'hackathon')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Punkty')),
                ('comment', models.TextField(blank=True, verbose_name='Komentarz')),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.criterion')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projects.project')),
            ],
            options={
                'unique_together': {('jury', 'project', 'criterion')},
            },
        ),
    ]
