# Generated by Django 6.0.3 on 2026-03-24 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Członek jury (QR)',
                'verbose_name_plural': 'Członkowie jury (QR)',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Ocena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jury_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='judging.jurymember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Głos',
                'verbose_name_plural': 'Głosy',
                'unique_together': {('jury_member', 'project')},
            },
        ),
    ]
