# Generated by Django 6.0.3 on 2026-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_jurymember_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurymember',
            name='session_active',
            field=models.BooleanField(default=False, verbose_name='Sesja aktywna'),
        ),
    ]
