# Generated by Django 6.0.3 on 2026-03-24 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0003_jurymember_session_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurymember',
            name='session_active',
        ),
        migrations.CreateModel(
            name='JurySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jury_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='judging.jurymember', verbose_name='Przypisany juror')),
            ],
        ),
    ]
