# Generated by Django 6.0.3 on 2026-03-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0005_vote_criterion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='score',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='score',
            name='jury',
        ),
        migrations.RemoveField(
            model_name='score',
            name='project',
        ),
        migrations.DeleteModel(
            name='JuryAssignment',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
