# Generated by Django 6.0.3 on 2026-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('participant', 'Uczestnik'), ('admin', 'Administrator')], default='participant', max_length=20),
        ),
    ]
