# Generated by Django 6.0.3 on 2026-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('date_start', models.DateTimeField(verbose_name='Data rozpoczęcia')),
                ('date_end', models.DateTimeField(verbose_name='Data zakończenia')),
                ('submit_deadline', models.DateTimeField(verbose_name='Deadline oddania projektów')),
                ('status', models.CharField(choices=[('planned', 'Planowany'), ('active', 'Aktywny'), ('judging', 'Ocenianie'), ('finished', 'Zakończony')], default='planned', max_length=20, verbose_name='Status')),
                ('max_team_size', models.PositiveIntegerField(default=5, verbose_name='Max wielkość zespołu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
    ]
