# Generated by Django 6.0.3 on 2026-03-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'W trakcie'), ('submissions_closed', 'Zgłoszenia zamknięte'), ('jury_review', 'Ocenianie jury'), ('results_announced', 'Wyniki ogłoszone')], default='in_progress', max_length=30, verbose_name='Status globalny')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_status', to='hackathon.hackathon', verbose_name='Aktywny hackathon')),
            ],
            options={
                'verbose_name': 'Status hackatonu',
                'verbose_name_plural': 'Status hackatonu',
            },
        ),
        migrations.CreateModel(
            name='PresentationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_order', models.JSONField(blank=True, default=list, verbose_name='Kolejność projektów (lista ID)')),
                ('current_index', models.IntegerField(default=0, verbose_name='Aktualny indeks')),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project', verbose_name='Aktualny projekt')),
                ('hackathon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='hackathon.hackathon')),
            ],
        ),
    ]
