# Generated by Django 6.0.3 on 2026-03-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_hackathonstatus_presentationsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HackathonStatus',
        ),
    ]
